config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "locations#recentlocations"
  get "location/:id/plants", to: "plants#plantslocation"
  get "homepage", to: "locations#recentlocations"
  get "profile", to: "users#profile"
  get "location/:id/edit", to: "logs#edit", as: :edit
  patch "location/:id", to: "logs#update"
  get "logs", to: "logs#index"
  get "landing", to: "pages#home"

  resources :locations do
    resources :plants, only: %i[new create]
  end

  resources :plants, except: %i[new create]  do
    resources :logs, only: %i[index new create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :user
  has_many :plants, dependent: :destroy
  has_one_attached :photo

  validates :name, uniqueness: true, presence: true
end

app/models/log.rb
class Log < ApplicationRecord
  belongs_to :plant
  after_create :level_up

  validates :content, presence: true
  validates :categories, inclusion: { in: %w[healthy water trim soil] }

  def level_up
    log_count = plant.logs.count

    if (log_count >= 0) && (log_count <= 3)
      plant.update(level: 0)
    elsif (log_count >= 4) && (log_count <= 7)
      plant.update(level: 1)
    elsif (log_count >= 8) && (log_count <= 11)
      plant.update(level: 2)
    else
      plant.update(level: 3)
    end
  end
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :location
  has_many :logs, dependent: :destroy

  validates :categories, inclusion: { in: ['person', 'moment'] }
  validates :name, :categories, presence: true
  accepts_nested_attributes_for :logs

  before_validation :set_default_state, :set_default_level, on: :create

  def check_state
    plantlog = logs.last.created_at
    days_difference = Time.current - plantlog
    if days_difference >= 3.days
      update(state: "needs caring")
    else
      update(state: "healthy")
    end
  end
  private


  def set_default_state
    self.state ||= 'healthy'
  end

  def set_default_level
    self.level ||= 0
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :locations, dependent: :destroy
  has_many :plants, through: :locations

  validates :username, uniqueness: true, presence: true
  validates :garden_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    # TODO: ADD THE OTHER PARAMETERS HERE AND MIGRATION
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[username garden_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    # TODO: ADD THE OTHER PARAMETERS AND MIGRATION
    devise_parameter_sanitizer.permit(:account_update, keys: %i[username garden_name])
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: %i[show]

  def recentlocations
    @status = Location.joins(:plants)
                      .where(user: current_user) # Ensure we only get the current user's locations
                      .where(plants: { state: ["needs caring"] })
                      .group('locations.id')
                      .limit(6)
    @recent = Location.joins(:plants)
                      .where(user: current_user)
                      .select('locations.*, MAX(plants.updated_at) as last_plant_update')
                      .group('locations.id')
                      .order('last_plant_update DESC')
                      .limit(4)
    @locations = Location.where(user: current_user)
    @plants = Plant.all
  end

  def index
    @locations = Location.where(user: current_user)
  end

  def show
    @location = Location.find(params[:id])
    @plant = Plant.new
  end

  def new
    @location = Location.new
  end

  def create
    @location = Location.new(location_params)
    @location.user_id = current_user.id
    if @location.save
      redirect_to location_path(@location)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_location
    @location = Location.find(params[:id])
  end

  def location_params
    params.require(:location).permit(:name, :updated_at, :photo)
  end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :set_plant, only: %i[index create new]
  # before_action :set_logs, only: %i[create]

  def index
    @logs = @plant.logs
  end

  def new
    @log = Log.new
    @location = @plant.location
  end

  def create
    @log = Log.new(log_params)
    @log.plant = @plant
    @location = @plant.location
    if @log.save
      redirect_to location_path(@location), notice: "Log was successfully updated."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @log.plant = @plant
    if @log.update(log_params)
      redirect_to log_path(@log), notice: "Log was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_logs
    @log = Log.find(params[:id])
  end

  def set_plant
    @plant = Plant.find(params[:plant_id])
  end

  def log_params
    params.require(:log).permit(:content, :categories)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]
  def home
    @exclude_footer = true
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :set_location, only: %i[new create]
  def index
    @plants = current_user.plants
    @plants.each(&:check_state)
    @status = current_user.plants
                          .where(state: "needs caring")
                          .limit(6)
  end

  def new
    @plant = Plant.new
    @log = Log.new
  end

  def create
    @plant = Plant.new(name: plant_params.dig(:name), categories: plant_params.dig(:categories))
    @plant.location = @location

    if @plant.save
      create_log
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_location
    @location = Location.find(params[:location_id])
  end

  def set_plant
    @plant = Plant.find(params[:id])
  end

  def plant_params
    params.require(:plant).permit(:name, :categories, log: {})
  end

  def create_log
    @log = Log.new(content: params["plant"]["log"]["content"])
    @log.plant = @plant
    @log.categories = "healthy"


    if @log.save
      redirect_to location_path(@location)
    else
      render :new, status: :unprocessable_entity
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def profile
    @user = current_user

  end

  private

  def user_params
    params.require(:user).permit(:username, :garden_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_container_footer.html.erb
<div class="container-footer fixed-bottom" data-controller="color-button">
  <ul>
    <li>
      <%= link_to homepage_path do %>
        <i class="fa-solid fa-house <%= request.fullpath === '/homepage' ? "active" : "" %>"></i>
      <% end %>
    </li>
    <li>
      <%= link_to plants_path do %>
        <i class="fa-solid fa-seedling <%= request.fullpath === '/plants' ? "active" : "" %>"></i>
      <% end %>
    </li>
    <li>
      <%= link_to locations_path do %>
        <i class="fa-solid fa-map <%= request.fullpath === '/locations' ? "active" : "" %>"></i>
      <% end %>
    </li>
    <li>
      <%= link_to profile_path do %>
        <i class="fa-solid fa-user <%= request.fullpath === '/profile' ? "active" : "" %>"></i>
      <% end %>
    </li>
  </ul>
</div>

app/views/layouts/_new_location_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <%= simple_form_for Location.new do |f| %>
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">New Location</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
          <%= f.input :name, input_html: {value: "", style: "border: 3px solid #A8E063"} %>
          <%= f.input :photo, as: :file %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn-primary-mod" data-bs-dismiss="modal">Close</button>
        <button type="submit" class="btn-primary-mod">Create</button>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlissfulBlooms - Practice your gratitude</title>
    <%= favicon_link_tag 'favicon-32x32.png' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%# <%= render "shared/flashes" %>

    <%= yield %>

    <%= render "layouts/new_location_modal" %>
    <%= render "layouts/container_footer" unless @exclude_footer %>
  </body>
</html>

app/views/locations/_form_location.html.erb
<div class="location-form-container d-flex justify-content-center mx-auto">
  <div>
    <%= simple_form_for @location do |f| %>
      <%= f.input :name %>

      <%= f.submit "Create!", class: "btn-normal-submit" %>
      <%= link_to "Cancel", locations_path, class: "btn btn-outline btn-md" %>
    <% end %>
  </div>
</div>

app/views/locations/_modal.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Create a new plant in <%= location.name %></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= simple_form_for [location, plant] do |f| %>
          <%= f.input :name %>
          <%= f.submit %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/locations/index.html.erb
<div class="container-plant">
  <div class="background-top fixed-top">
    <div class="d-flex justify-content-between">
      <%= image_tag('Logo.png', class: "logo") %>
      <%= image_tag('CatIcon.png', class: "cat") %>
    </div>
    <div class="message-container">
      <div>
        <p style="font-size: 14px;" class="mx-2 headerp">
        You can find all your locations here! Or if you would like you can create a new one ! <strong>MEOW :3 </strong>
        </p>
      </div>
    </div>
  </div>

  <!-- Button trigger modal -->
  <div class="create_plant d-flex justify-content-end mt-5">
    <a type="button" data-bs-toggle="modal" data-bs-target="#exampleModal">
      <%= image_tag('catplusPNG.png', class: "create-cat grow") %>
    </a>
  </div>

  <div class="location-container" style="margin-top: 1.5rem; margin-bottom: 4rem;">
    <% @locations.each do |location| %>
      <div class="card d-flex justify-content-between">
        <div class="card-info">
        <% if location.photo.attached? %>
          <div>
          <%= cl_image_tag location.photo.key, height: 300, width: 400, crop: :fill , class: "image_location" %>
          </div>
        <% else %>
          <div>
          <%= image_tag('add-picture.svg', class: "image_location") %>
          </div>
        <% end %>
          <div class="location-text">
            <h2 style="margin-bottom: 0px"><strong><%= location.name.capitalize %></strong></h2>
            <p style="margin-bottom: 0px"> plants🪴: <%= location.plants.count %></p>
            <p class="pt-3" style="z-index: 3;"><%= link_to "Go",location_path(location), class: "btn-normal" %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/locations/recentlocations.html.erb
<div class="background-top" data-controller="messages">
  <div class="d-flex justify-content-between">
    <%= image_tag('Logo.png', class: "logo") %>
    <%= image_tag('CatIcon.png', class: "cat") %>
  </div>
  <div class="message-container-recent"> <%# TODO: ADD RUBY AFTER WITH CONDITIONS %>
    <div>
      <p style="font-size: 14px;" class="mx-2 headerp">
      <% if @locations.empty? %>
        <strong><%= current_user.username.capitalize %></strong>. This page will display your recent locations interactions🪴. To start make sure to create your first location, at the 3rd tab.
      <% elsif @status.any?  %>
        Welcome back <strong><%= current_user.username.capitalize %></strong> you have plants🪴 to take care of at
        <% @status.each_with_index do |location, index| %>
          <strong><%= location.name %></strong><%= (index == @status.size - 1 ? "..." : ", ") %>
        <% end %>
      <% elsif @plants.count.zero? %>
        Meowdy <strong><%= current_user.username.capitalize %></strong>. In order to check your recents locations, you need
        to plant your first seed in your desired location by clicking the + button.
      <% else %>
        Welcome back <strong><%= current_user.username.capitalize %></strong>, all your plants🪴 are healthy meowie! Keep up the good work!
      <% end %>
      </p>
    </div>
  </div>
</div>


<div class="recents-container">
  <% @recent.each do |location| %>
    <div class="recent-container">
      <div class="container-info">
        <% if location.photo.attached? %>
          <div class="placeholder" style="background-image: url('<%= cl_image_path location.photo.key, height: 300, gravity: "auto", crop: :fill %>'); opacity: 1">
          </div>
        <% else %>
          <div class="placeholder2">
          </div>
        <% end %>
        <div style="margin-left: 1rem; margin-top: 0.5rem;">
          <h4 class="location-name"><%= location.name.capitalize %></h4>
          <p><%= location.plants.count %> plants🪴<p>
        </div>
        <div class="text-center" style="margin-top: 3rem;">
          <%= link_to "Go", location_path(location), class: "btn-normal" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/locations/show.html.erb
<div class="container-plant">
  <div class="background-top fixed-top">
    <div class="d-flex justify-content-between">
      <%= image_tag('Logo.png', class: "logo") %>
      <%= image_tag('CatIcon.png', class: "cat") %>
    </div>
    <div class="message-container"> <%# TODO: ADD RUBY AFTER WITH CONDITIONS %>
      <div>
        <p style="font-size: 14px;" class="mx-2 headerp">
          <% if @location.plants.empty? %>
            Welcome to your new location <strong><%= current_user.username.capitalize %></strong>, now you only need to start by planting your first seed mEEEwr.
          <% else %>
            <strong><%= current_user.username.capitalize %></strong>, please remember that it only takes you 2 minutes
            to take care of your plants🪴.
          <% end %>
        </p>
      </div>
    </div>
  </div>

  <div type="button" class ="create_plant d-flex justify-content-end mt-5">
      <%= link_to image_tag('catplusPNG.png', class: "create-cat grow"), new_location_plant_path(@location)%>
  </div>

  <div class="location-container" style="margin-top: 1.5rem; margin-bottom: 4rem;">
    <% @location.plants.each do |plant| %>
      <div class="card">
        <div class="card-info-plant">
          <div>
            <% if plant.level == 1 %>
              <%= image_tag('Level2.png', class: "image_plants mt-1") %>
            <% elsif plant.level == 2 %>
              <%= image_tag('Level3.png', class: "image_plants mt-1") %>
            <% elsif plant.level == 3 %>
              <%= image_tag('Level4.png', class: "image_plants mt-1") %>
            <% else %>
              <%= image_tag('Level1.png', class: "image_plants mt-1") %>
            <% end %>
          </div>
          <div class="location-text">
            <h2 style="margin-bottom: 0px"><strong><%= plant.name.capitalize%></strong></h2>
            <p style="margin-bottom: 0px">
            <% time = Time.new %>
            <% days_difference = (time.to_date - plant.created_at.to_date).to_i %>
            <% remaining_days = days_difference % 365 %>
            <% days = remaining_days % 30 %>
            <% months = remaining_days / 30 %>
            <% years = days_difference / 365 %>
            <% if years > 0 %>
              <%= "#{years} years old!" %>
            <% elsif months > 0 %>
              <%= "#{months} months old!" %>
            <% else %>
              <%= "#{days} days old!" %>
            <% end %>
            </p>
            <p><%= plant.state.capitalize %></p>
            <div class="level-container text-center">
              <p style="margin-bottom: 0px">
                <% if plant.level == 0 %>
                  Lvl.0
                <% else %>
                  <%= "Lvl.#{plant.level}" %>
                <% end %>
              </p>
            </div>
          </div>
        </div>
        <div class="btn btn-outline-go">
          <%= link_to "Go", new_plant_log_path(plant) %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/logs/edit.html.erb
<div class="background-top">
  <div class="d-flex justify-content-between">
    <%= image_tag('Logo.png', class: "logo") %>
    <%= image_tag('CatIcon.png', class: "cat") %>
  </div>
  <div>
    <h2 class="headers"></h2>
  </div>
</div>

<div class="container-carousel">

  <div class="carousel-card position-absolute top-0 end-50">
    <div class="card-info" style="gap: 1rem">
      <%= link_to location_path do %>
        <i class="fa-solid fa-chevron-left"></i>
      <% end %>
      <h2 style="text-align: center">🪴 Plant Name 🪴</h2>
    </div>


    <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-inner d-flex justify-content-center">
        <div class="carousel-container ">
          <div class="carousel-item active">
            <%= image_tag('potted-plant.webp', class: "carousel-img") %>
          </div>
        </div>
      </div>
      <div class="actions-wrapper">
        <div class="actions-box">
          <div class="card-info-drop mb-2">
            <label for="exampleFormControlFile1", style="text-align: center">What's your action?</label>
          </div>
          <div class="btn-action-group">
            <div class="btn-group" role="group" aria-label="Basic outlined example">
              <button type="button" class="btn btn-action-card"><%= image_tag('WaterCan.png', class: "btn-action-img") %></button>
              <button type="button" class="btn btn-action-card"><%= image_tag('trimmer.png', class: "btn-action-img") %></button>
              <button type="button" class="btn btn-action-card"><%= image_tag('soil 1.png', class: "btn-action-img") %></button>
            </div>
          </div>
        </div>
      </div>


    </div>
  </div>
</div>

<%# <div class="card-info-drop mt-2">
            <label for="exampleFormControlFile1", style="text-align: center">What's your action?</label>
          </div>
          <select class="form-control form-control-sm mt-1" >
            <option>Water 💦</option>
            <option>Trim ✂️</option>
            <option>Soil 🌱</option>
          </select>
          <div class="card-info-drop mt-2">
            <button type="submit" class="btn-normal-submit-drop">Go</button>
          </div> %>

app/views/logs/index.html.erb
<div class="background-top ">
  <div class="d-flex justify-content-between">
    <%= image_tag('Logo.png', class: "logo") %>
    <%= image_tag('CatIcon.png', class: "cat") %>
  </div>
  <div>
    <h2 class="headers"><%= "BookLogs" %></h2>
  </div>
</div>

<div class="container-carousel">

  <div class="carousel-card position-fixed mx-auto top-0">
    <div class="card-info-log">
      <div class="back-arrow">
        <%= link_to plants_path do %>
          <i class="fa-solid fa-chevron-left"></i>
        <% end %>
      </div>
      <h2 style="text-align: center; color: #57AC30; font-weight: 500; font-size: 2rem"> <%= @plant.name.capitalize %></h2>
    </div>


    <div id="carouselExampleIndicators" class="carousel slide" data-bs-interval="false">
      <div class="carousel-inner d-flex justify-content-center">
        <div class="carousel-container ">
          <div class="carousel-item active">
            <% if @plant.level == 1 %>
              <%= image_tag('Level2.png', class: "image_plants2") %>
            <% elsif @plant.level == 2 %>
              <%= image_tag('Level3.png', class: "image_plants2") %>
            <% elsif @plant.level == 3 %>
              <%= image_tag('Level4.png', class: "image_plants2") %>
            <% else %>
              <%= image_tag('Level1.png', class: "image_plants2") %>
            <% end %>
            <div class="div-level-conatiner-plant">
              <div class="level-container-plant text-center">
              <p style="margin-bottom: 0px;">
                  <% if @plant.level == 0 %>
                    Lvl.0
                  <% else %>
                    <%= "Lvl.#{@plant.level}" %>
                  <% end %>
                </p>
              </div>
            </div>
          </div>
          <div class="carousel-item">
            <div class="background-log text-center">
              <%# TODO: fix this logs, to show specific plant log :) and fix carousel to stop moving automatically %>
              <p><% @logs.each do |log| %>
                <p style="color: #36454F; padding-right: 2px; padding-left: 2px;"><strong><%= log.created_at.strftime("%B %d %Y, %l:%M%P") %></strong></p>
                <p style="color: #36454F; padding-right: 2px; padding-left: 2px;"><%= log.content.capitalize %></p>
                <% end %>
              </p>
            </div>
          </div>
        </div>
      </div>

      <button class="arrow-btn carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
        <span class="fa-solid fa-angle-left" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="arrow-btn carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
        <span class="fa-solid fa-angle-right" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>

    </div>
  </div>
</div>

app/views/logs/show.html.erb
<div class="background-top ">
  <div class="d-flex justify-content-between">
    <%= image_tag('Logo.png', class: "logo") %>
    <%= image_tag('CatIcon.png', class: "cat") %>
  </div>
  <div>
    <h2 class="headers"><%= "BookLogs" %></h2>
  </div>
</div>

<div class="container-carousel">

  <div class="carousel-card position-absolute top-0 end-50">
    <div class="card-info" style="gap: 1rem">
      <%= link_to plants_path do %>
        <i class="fa-solid fa-chevron-left"></i>
      <% end %>
      <h2 style="text-align: center;"> 🪴 Plant Name 🪴</h2>
    </div>


    <div id="carouselExampleIndicators" class="carousel slide" data-bs-interval="false">
      <div class="carousel-inner d-flex justify-content-center">
        <div class="carousel-container ">
          <div class="carousel-item active">
            <%= image_tag('potted-plant.webp', class: "carousel-img") %>

          </div>
          <div class="carousel-item">
            <div class="background-log text-center">
              <%# TODO: fix this logs, to show specific plant log :) and fix carousel to stop moving automatically %>
              <p><%= @log.content %></p>
            </div>
          </div>
        </div>
      </div>

      <button class="arrow-btn carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
        <span class="fa-solid fa-angle-left" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="arrow-btn carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
        <span class="fa-solid fa-angle-right" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>

    </div>
  </div>
</div>

app/views/plants/index.html.erb
<div class="background-top fixed-top">
  <div class="d-flex justify-content-between">
    <%= image_tag('Logo.png', class: "logo") %>
    <%= image_tag('CatIcon.png', class: "cat") %>
  </div>
  <div class="message-container"> <%# TODO: ADD RUBY AFTER WITH CONDITIONS %>
    <div>
      <p style="font-size: 14px;" class="mx-2 headerp">
      <%# TODO: ADD ONLY 4 LOCATIONS WITH THE CONDITION  %>
      <% if @plants.empty? %>
          Meowdy <strong><%= current_user.username.capitalize %></strong>, as it's your first time here, in order to have plants🪴, you need
        to plant them in your desired location by clicking the + button.
      <% elsif @status.any? %>
        <strong><%= current_user.username.capitalize %></strong>, please make sure to take care of
        <% @status.each_with_index do |plant, index| %>
          <strong><%= "#{plant.name}🪴" %></strong><%=(index == @status.size - 1 ? "..." : ", ") %>
        <% end %>
      <% else %>
        <strong><%= current_user.username.capitalize %></strong>, you are doing an amazing job at taking care of your plants🪴. Keep it up!
      <% end %>
      </p>
    </div>
  </div>
</div>


<div class="location-container" style="margin-bottom: 4rem; margin-top: 11.8rem">
  <% @plants.each do |plant| %>
    <div class="card">
      <div class="card-info">
        <div>
          <% if plant.level == 1 %>
            <%= image_tag('Level2.png', class: "image_plants mt-3") %>
          <% elsif plant.level == 2 %>
            <%= image_tag('Level3.png', class: "image_plants mt-3") %>
          <% elsif plant.level == 3 %>
            <%= image_tag('Level4.png', class: "image_plants mt-3") %>
          <% else %>
            <%= image_tag('Level1.png', class: "image_plants mt-3") %>
          <% end %>
        </div>
        <div class="location-text">
          <h2 style="margin-bottom: 0px"><strong><%= plant.name.capitalize%></strong></h2>
          <p style="margin-bottom: 0px">State: <%=plant.state.capitalize %></p>
          <p style="margin-bottom: 0px">Last updated: <%= TimeDifference.between(Time.now, plant.logs.last.created_at).in_days.floor() %> days ago</p>
          <p class="pt-3"><%= link_to "Logs", plant_logs_path(plant), class: "btn-normal"%></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/plants/new.html.erb
<div class="background-top" data-controller="messages">
  <div class="d-flex justify-content-between">
    <%= image_tag('Logo.png', class: "logo") %>
    <%= image_tag('CatIcon.png', class: "cat") %>
  </div>
  <div class="message-container-create">
    <div>
      <p style="font-size: 14px;" class="mx-2 headerp">
        Your plant🪴 can either represent a person or a moment!
      </p>
    <div>
  </div>
</div>

<div class="container-carousel">
  <div class="new-plant-container position-fixed mx-auto top-0" ><%#TODO: change class name%>
    <div class="form-creation-plant" data-controller="categories-select">
      <%= simple_form_for [@location, @plant], url: location_plants_path do |f| %>
        <%= f.input :name %>
          <div class="images d-flex-even mb-3">
            <div class="p-image">
              <%= image_tag "person-2.png",id: "image1", height: 68, width: 72, data: { action: "click->categories-select#select", categories_select_target: "image1"} %>
            </div>
            <div class="p-image">
              <%= image_tag "moment-2.png",id: "image2", height: 68, width: 72, data: { action: "click->categories-select#select", categories_select_target: "image2"} %>
            </div>
          </div>
        <div class="radio-buttons-inline d-none">
          <%= f.input :categories, collection: [['Person', 'person'], ['Moment', 'moment']], as: :radio_buttons %>
        </div>
        <%= f.simple_fields_for @log do |m| %>
          <%= m.input :content, label: "Journal", input_html: { class: 'textarea-height' } %>
        <% end %>
        <%= f.submit "Create", class: "btn btn-primary-log" %>
      <% end %>
      <%= link_to "Cancel", location_path(@location.id), class: "cancel-btn d-flex justify-content-center mt-3 mx-auto" %>
    </div>
  </div>
</div>